# Generated by Django 3.1.1 on 2020-09-19 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Path',
            new_name='Post',
        ),
    ]
